[package]
name = "arithmetic-logic-unit"
version = "0.1.0"
authors = ["Maximilian Dorn <m.dorn.2003@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
